trigger:
  - main  # your default branch

pool:
  vmImage: 'windows-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew.bat'  # On Windows use gradlew.bat
    tasks: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/test/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
