trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: chmod +x gradlew
  displayName: 'Make gradlew executable (Linux/macOS only)'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/test/TEST-*.xml'
